import time, os

def func_variable():
    os.system("cls")
    print(" __      __        _       _     _            ")
    print(" \ \    / /       (_)     | |   | |           ")
    print("  \ \  / /_ _ _ __ _  __ _| |__ | | ___  ___  ")
    print("   \ \/ / _` | '__| |/ _` | '_ \| |/ _ \/ __| ")
    print("    \  / (_| | |  | | (_| | |_) | |  __/\__ \ ")
    print("     \/ \__,_|_|  |_|\__,_|_.__/|_|\___||___/ ")
    print()
    print("[1] ¿Que son?")
    print("[2] Tipos de datos")
    print("[3] Variables multiples")
    print("[4] Variables iguales")
    print("[5] Lista de objetos")
    print("[6] Suma de variables")
    print("[7] Salir")
    print()
    option = input("> ")
    if option == "1":
        print("Una variable es un contenedor para almacenar datos que se pueden usar en un programa")
        time.sleep(1)
        print("Puedes pensar en una variable como una etiqueta para un valor")
        time.sleep(1)
        print("Estructura: (Name) = (Value)")
        time.sleep(1)
        print()
        print("Ejemplo: x = 10")
        print("print(x)")
        print()
        print("Ejemplo: y = 'Hello'")
        print("print(y)")
        print()
        input("Presiona Enter para continuar...")
        func_variable()
    elif option == "2":
        print("En python hay 3 tipos de datos:")
        time.sleep(1)
        print("int = Número entero")
        print("str = Cadena de texto")
        print("float = Número decimal")
        time.sleep(1)
        print()
        print("x = 10")
        print("Ejemplo: print(int(x))  --> Nos dará 10")
        print("Ejemplo: print(str(x))  --> Nos dará '10'")
        print("Ejemplo: print(float(x))  --> Nos dará 10.0")
        time.sleep(1)
        print()
        print("Tambien puedes sacar el tipo de información de una variable")
        print("y = 'Hello'")
        print("Ejemplo: print(type(x))  --> Nos dará <class 'int'>")
        print("Ejemplo: print(type(y))  --> Nos dará <class 'str'>")
        time.sleep(1)
        print()
        input("Presiona Enter para continuar...")
        func_variable()
    elif option == "3":
        print("Puedes asignar multiples variables en una sola linea")
        time.sleep(1)
        print()
        print("a, b, c = 5, 3.2, 'Hello'")
        print("print(a)  --> Nos dará 5")
        print("print(b)  --> Nos dará 3.2")
        print("print(c)  --> Nos dará 'Hello'")
        time.sleep(1)
        print()
        input("Presiona Enter para continuar...")
        func_variable()
    elif option == "4":
        print("Puedes asignar multiples variables con el mismo valor")
        time.sleep(1)
        print()
        print("x = y = z = 'Same'")
        print("print(x)  --> Nos dará 'Same'")
        print("print(y)  --> Nos dará 'Same'")
        print("print(z)  --> Nos dará 'Same'")
        time.sleep(1)
        print()
        input("Presiona Enter para continuar...")
        func_variable()
    elif option == "5":
        print("Puedes asignar multiples variables en una sola linea")
        time.sleep(1)
        print()
        print("fruits = ['apple', 'banana', 'cherry']")
        print("a, b, c = fruits")
        print("print(a)  --> Nos dará 'apple'")
        print("print(b)  --> Nos dará 'banana'")
        print("print(c)  --> Nos dará 'cherry'")
        time.sleep(1)
        print()
        input("Presiona Enter para continuar...")
        func_variable()
    elif option == "6":
        print("Puedes sumar variables")
        time.sleep(1)
        print()
        print("x = 5")
        print("y = 8")
        print("z = 'hola'")
        print("print(x + y)  --> Nos dará 13")
        print("print(z + z + str(x))  --> Nos dará 'hola hola 5' (No se puede sumar un str con un int)")
        print("print(x, y, z)  --> Nos dará 5 8 hola")
        time.sleep(1)
        print()
        input("Presiona Enter para continuar...")
        func_variable()
    elif option == "7":
        os.system("cls")
        from app import menu
        menu()